# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  displayName: InsertDotNetSdk
  inputs:
    version: '6.x'
- task: DotNetCoreCLI@2
  displayName: restore
  inputs:
    command: 'restore'
    workingDirectory: ./src
    projects: '**/*.csproj'
    feedsToUse: 'select'
    #vstsFeed: 'my-vsts-feed' # A series of numbers and letters
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    workingDirectory: ./src
    arguments: '--configuration $(buildConfiguration)'
  displayName: 'dotnet build $(buildConfiguration)'
#- task: DotNetCoreCLI@2
#  displayName: 'Test'
#  inputs:
#    command: test
#    projects: '**/*Test/*.csproj'
#    workingDirectory: ./src
#    arguments: '--configuration $(buildConfiguration)'
