name: .NET buld

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3   
      with:
       fetch-depth: "0"
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies
      run: dotnet restore
                            
    - name: Build
      run:  dotnet build -c Release --no-restore
      
    - name: Analyze with SonarCloud
      uses: sonarsource/sonarcloud-github-action@master
      with:
        projectBaseDir: my-custom-directory
        args: >
          -Dsonar.organization=x2031
          -Dsonar.projectKey=x2031_Good.Admin
          -Dsonar.python.coverage.reportPaths=coverage.xml
        #-Dsonar.test.exclusions=tests/**
        #-Dsonar.tests=tests/
          
      
    # - name: SonarScan
     #  uses: highbyte/sonarscan-dotnet@v2.1.3              
      # with:
      #     sonarProjectKey: x2031_Good.Admin
      #     sonarProjectName: Good.Admin
      #     sonarOrganization: x2031
       #    dotnetBuildArguments: .
          #dotnetTestArguments: ./src --logger trx --collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover
          #sonarBeginArguments: /d:sonar.cs.opencover.reportsPaths="**/TestResults/**/coverage.opencover.xml" -d:sonar.cs.vstest.reportsPaths="**/TestResults/*.trx"
  
env:
 SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
 GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
      
      
