name: .NET buld

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:  
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup .NET 6.0
        uses: actions/setup-dotnet@v3.0.2
        with:
          dotnet-version: 6.0.x
      - name: SonarScan
        uses: highbyte/sonarscan-dotnet@v2.1.3
        with:
          sonarProjectKey: x2031_Good.Admin.Public
          sonarProjectName: Good.Admin
          sonarOrganization: x2031
          dotnetBuildArguments: Good.Admin.API
          dotnetDisableTests: true
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: "0"
      - name: Setup .NET
        uses: actions/setup-dotnet@v3.0.2
        with:
          dotnet-version: 6.0.x
      - name: clean
        run: dotnet clean     
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build -c Release --no-restore
