name: .NET buld

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3   
      with:
       fetch-depth: "0"
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies
      run: dotnet restore
                            
    - name: Build
      run:  dotnet build -c Release --no-restore
      
    # - name: SonarScan
     #  uses: highbyte/sonarscan-dotnet@v2.1.3              
      # with:
      #     sonarProjectKey: x2031_Good.Admin
      #     sonarProjectName: Good.Admin
      #     sonarOrganization: x2031
       #    dotnetBuildArguments: .
          #dotnetTestArguments: ./src --logger trx --collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover
          #sonarBeginArguments: /d:sonar.cs.opencover.reportsPaths="**/TestResults/**/coverage.opencover.xml" -d:sonar.cs.vstest.reportsPaths="**/TestResults/*.trx"
    - name: Analyze with SonarCloud 
      uses: SonarSource/sonarcloud-github-action@master
      with:
          # Additional arguments for the sonarcloud scanner
          args:             
            # Unique keys of your project and organization. You can find them in SonarCloud > Information (bottom-left menu)
            # mandatory
            -Dsonar.projectKey=x2031_Good.Admin
            -Dsonar.organization=x2031
            # Comma-separated paths to directories containing main source files.
            #-Dsonar.sources= # optional, default is project base directory
            # When you need the analysis to take place in a directory other than the one from which it was launched
            #-Dsonar.projectBaseDir= # optional, default is .
            # Comma-separated paths to directories containing test source files.
            #-Dsonar.tests= # optional. For more info about Code Coverage, please refer to https://docs.sonarcloud.io/enriching/test-coverage/overview/
            # Adds more detail to both client and server-side analysis logs, activating DEBUG mode for the scanner, and adding client-side environment variables and system properties to the server-side log of analysis report processing.
            #-Dsonar.verbose= # optional, default is false             
env:
 SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
 GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
      
      
