name: .NET buld

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3   
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies
      run: dotnet restore
                            
    - name: Build
      run:  dotnet build -c Release --no-restore
      
  Analysis:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
        
    - name: SonarScanner Analysis
      uses: highbyte/sonarscan-dotnet@v2.1.3
      with:
        # The key of the SonarQube project
        sonarProjectKey: x2031_Good.Admin
        # The name of the SonarQube project
        sonarProjectName:  Good.Admin
        # The name of the SonarQube organization in SonarCloud. For hosted SonarQube, skip this setting.
        #sonarOrganization: x2031
        buildCommand: dotnet build .     
      
env:
    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
      
      
