name: SonarScan
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: "0"
      - name: SonarScan
        uses: highbyte/sonarscan-dotnet@v2.1.2
              
        with:
          sonarProjectKey: x2031_Good.Admin
          sonarProjectName: Good.Admin
          sonarOrganization: x2031
          dotnetTestArguments: --logger trx --collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover
          sonarBeginArguments: /d:sonar.cs.opencover.reportsPaths="**/TestResults/**/coverage.opencover.xml" -d:sonar.cs.vstest.reportsPaths="**/TestResults/*.trx"
env:
 SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
 GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
